name: Bug Report
description: Create a report to help us fix bugs in EmuFlight Configurator.
labels: ["Template: Bug"]
body:

  - type: markdown
    attributes:
      value: |
        # Please fill all the fields with the required information

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Setup

  - type: input
    attributes:
      label: Configurator version
      description: Specify the full version of the configurator (as displayed in the app, bottom right corner).
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System version
      description: Specify the full version of the the opretaing System (e.g. Windows 11, OSX 12, Ubuntu 22.04).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Flight controller configuration
      description: |
        If this bug is related to a specific flight controller and/or configuration please specify it here.
        Create a `diff` and post it here. In some cases, maybe a `dump` is better.
      placeholder: |
          # PASTE HERE THE OUTPUT OF `diff` or `dump` COMMAND FROM THE CLI TAB
      render: txt

  - type: markdown
    attributes:
      value: |
        # Other information

  - type: textarea
    attributes:
      label: Add any other context about the problem that you think might be relevant here

  - type: markdown
    attributes:
      value: |
        # Any screenshots may be added to a follow-up comment once the issue is opened.
