blank_issues_enabled: false
contact_links:
  - name: Firmware Bugs
    url: https://github.com/emuflight/EmuFlight/issues/
    about: EmuFlight Firmware Issue Tracker
  - name: EmuFlight Support and Developers Channel
    url: https://discord.gg/BWqgBg3
    about: EmuFlight Discord
